# Generated by Django 5.1.7 on 2025-04-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('regular', 'Regular Bike'), ('electric', 'Electric Bike')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('battery_capacity', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
